### ISSUE TITLE
Compilation fails on Ubuntu 26.04: clock_gettime and CLOCK_REALTIME undeclared

### ISSUE THREAD

**Issue by shororxor** [metascriptlang/compiler#1]
## System Specification

* **OS:** Ubuntu 26.04
* **Architecture:** Linux x86_64

## Problem

After installing the `msc` compiler by following the installation guide, I tried to compile the following simple TypeScript program:

```typescript
// hello.ms
console.log("hello world");
```

However, the compilation fails with the following error:
```
msc run hello.ms
```

```text
/home/$HOME/.metascript/runtime/core/datetime.c: In function ‘msTimeNow’:
/home/$HOME/.metascript/runtime/core/datetime.c:23:9: error: implicit declaration of function ‘clock_gettime’ [-Wimplicit-function-declaration]
   23 |         clock_gettime(CLOCK_REALTIME, &ts);
      |         ^~~~~~~~~~~~~
/home/$HOME/.metascript/runtime/core/datetime.c:23:23: error: ‘CLOCK_REALTIME’ undeclared (first use in this function)
   23 |         clock_gettime(CLOCK_REALTIME, &ts);
      |                       ^~~~~~~~~~~~~~
/home/$HOME/.metascript/runtime/core/datetime.c:23:23: note: each undeclared identifier is reported only once for each function it appears in
/home/$HOME/.metascript/runtime/core/datetime.c: In function ‘msTimeMonotonic’:
/home/$HOME/.metascript/runtime/core/datetime.c:38:23: error: ‘CLOCK_MONOTONIC’ undeclared (first use in this function)
   38 |         clock_gettime(CLOCK_MONOTONIC, &ts);
      |                       ^~~~~~~~~~~~~~~
error: @compile failed for /home/$HOME/.metascript/runtime/core/datetime.c (exit 1)
```

To verify whether this was a system or compiler/environment issue, I tested `clock_gettime` with a minimal C program:

```c
#include <time.h>
#include <stdio.h>

int main() {
    struct timespec ts;
    clock_gettime(CLOCK_REALTIME, &ts);
    printf("tv_sec: %ld", ts.tv_sec);
    return 0;
}
```

This compiles and runs successfully on my system, so the issue does not appear to be related to `clock_gettime` support on Ubuntu 26.04 itself.

I also tried building the project from source using:

```bash
msc build --gc=drc --release src/index.ms
```

but the build also fails with numerous warnings/errors.

### Additional Information

I will take a closer look at the source code to investigate the issue. If I find a necessary fix, I would be happy to submit a PR.

The project looks very interesting, and I'm looking forward to exploring it further!

**Comment by shororxor** [comment]
Well, testing on Macos yielded no problem.

**Comment by fluctlight-kayaba** [comment]
@shororxor thank you for trying!

have just released [latest version 0.2.50](https://github.com/metascriptlang/compiler/releases/tag/v0.2.50) - run installation script again to get the latest version - that works on Ubuntu 26.04 x86_64 when I test, this version is more stable than `0.2.19` however it still early - if you face other problem please open new issuse.

**Comment by shororxor** [comment]
Nice it works! Thank you!
